"""
Constant values for SplitFlapDrum
"""

WHEEL_THICKNESS = 1.6

CENTER_DIAMETER_BOTTOM = 17
CENTER_DIAMETER_TOP = 10
CENTER_HEIGHT = 17.4

SCREW_DISTANCE = 5.2
SCREW_DIAMETER = 2.3
SCREW_BLOCK_HEIGHT_INNER = 6
SCREW_ROTATION_ANGLE = -11.6
SCREW_BORE_DIAMETER = 4.5
SCREW_BORE_DEPTH = 2

INSERT_DIAMETER = 6
INSERT_DEPTH = 5

DRUM_DIAMETER = 55.2
DRUM_THICKNESS = 1.2
DRUM_HEIGHT_INNER = 6
DRUM_HEIGHT_OUTER = 40

BAR_LENGTH = DRUM_DIAMETER - 0.6
BAR_WIDTH = 1
BAR_HEIGHT_CENTER = 10
BAR_HEIGHT_OUTER = 7

BAR_COUNTER_THICKNESS = 1
BAR_COUNTER_WIDTH = 3
BAR_COUNTER_GAP = 1.15
BAR_COUNTER_HEIGHT = 14
BAR_COUNTER_START_Z = DRUM_HEIGHT_OUTER - SCREW_BLOCK_HEIGHT_INNER - BAR_COUNTER_HEIGHT
